version: '3'

services:
  app:
    build: .
    container_name: backend-api-nodeks
    restart: always
    command: npm run dev
    ports:
     - "3333:3333"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules